# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestSmokeTestSuite():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
    self.base_url = "http://127.0.0.1:5500/teton/1.6"
    self.wait = WebDriverWait(self.driver, 10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homePageTest(self):
    self.driver.get(f"{self.base_url}/index.html")
    self.driver.set_window_size(1200, 800)
    
    # Wait for header logo
    self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".header-logo")))
    
    # Check page title and heading
    assert self.driver.title == "Teton Idaho CoC"
    assert self.driver.find_element(By.CSS_SELECTOR, "h1").text == "Teton Idaho"
    
    # Check for Join link and click it
    join_link = self.wait.until(EC.presence_of_element_located((By.LINK_TEXT, "Join")))
    join_link.click()
    
    # Verify join page loaded
    self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".join-wizard-main")))
  
  def test_directoryPageTest(self):
    self.driver.get(f"{self.base_url}/directory.html")
    
    # Wait for directory data container
    directory_data = self.wait.until(
        EC.presence_of_element_located((By.ID, "directory-data"))
    )
    
    # Wait for JavaScript to execute and check readyState
    self.wait.until(
        lambda driver: driver.execute_script("return document.readyState") == "complete"
    )
    
    # Wait longer for dynamic content
    time.sleep(3)
    
    # Debug print
    print("Directory data content:", directory_data.get_attribute('innerHTML'))
    
    # Check if any content exists
    content = directory_data.get_attribute('innerHTML').strip()
    if not content:
        print("Page source:", self.driver.page_source)
        print("JavaScript ready state:", self.driver.execute_script("return document.readyState"))
    
    assert len(content) > 0
    assert "Teton" in directory_data.text
    
    # Switch to list view
    list_btn = self.wait.until(EC.element_to_be_clickable((By.ID, "directory-list")))
    list_btn.click()
    
    time.sleep(1)  # Wait for view change
    assert "Teton" in directory_data.text
  
  def test_joinPageTest(self):
    self.driver.get(f"{self.base_url}/join.html")
    
    # Wait for JavaScript to execute
    self.wait.until(
        lambda driver: driver.execute_script("return document.readyState") == "complete"
    )
    
    # Wait for join wizard
    join_wizard = self.wait.until(
        EC.presence_of_element_located((By.CLASS_NAME, "join-wizard-main"))
    )
    
    # Wait for form with longer timeout
    self.wait = WebDriverWait(self.driver, 20)
    form = self.wait.until(
        EC.presence_of_element_located((By.TAG_NAME, "form"))
    )
    
    # Debug print
    print("Form HTML:", form.get_attribute('innerHTML'))
    
    # Find all inputs and print their attributes
    inputs = form.find_elements(By.TAG_NAME, "input")
    print("Found inputs:", [(i.get_attribute('type'), i.get_attribute('name')) for i in inputs])
    
    # Try to find any text input
    text_inputs = form.find_elements(By.CSS_SELECTOR, "input[type='text']")
    assert len(text_inputs) >= 2, f"Expected at least 2 text inputs, found {len(text_inputs)}"
    
    # Fill in the form
    text_inputs[0].send_keys("John")
    text_inputs[1].send_keys("Doe")
  
  def test_adminPageTest(self):
    self.driver.get(f"{self.base_url}/admin.html")
    
    # Wait for and fill username
    username_field = self.wait.until(EC.presence_of_element_located((By.NAME, "username")))
    username_field.send_keys("wronguser")
    
    # Fill password
    password_field = self.driver.find_element(By.NAME, "password")
    password_field.send_keys("wrongpass")
    
    # Click login
    login_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".mysubmit")))
    login_button.click()
    
    # Check error message
    error_message = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, ".errorMessage")))
    assert error_message.text == "Invalid username and password."
  
